/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package changepassword;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 * @author ToNio
 */
public class ChangePasswordView extends javax.swing.JFrame
{

    /**
     * Creates new form ChangePasswordView1
     */
    public ChangePasswordView()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jOptionPane1 = new javax.swing.JOptionPane();
        changePasswordTitle = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        userNameField = new java.awt.TextField();
        passwordField = new javax.swing.JPasswordField();
        retypePasswordLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        newPasswordLabel = new javax.swing.JLabel();
        retypeNewPasswordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        changePasswordTitle.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        changePasswordTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePasswordTitle.setText("Change Password");

        okButton.setText("OK");

        cancelButton.setText("Cancel");

        passwordField.setToolTipText("");

        retypePasswordLabel.setText("Retype Password");

        newPasswordLabel.setText("New Password");

        passwordLabel.setText("Password");

        usernameLabel.setText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(105, 105, 105).addComponent(changePasswordTitle).addContainerGap(132, Short.MAX_VALUE)).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(okButton).addComponent(retypePasswordLabel))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(newPasswordField).addComponent(passwordField).addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE).addComponent(retypeNewPasswordField)).addComponent(cancelButton)).addGap(34, 34, 34)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addComponent(changePasswordTitle).addGap(27, 27, 27).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(usernameLabel).addGap(0, 0, Short.MAX_VALUE)).addGroup(layout.createSequentialGroup().addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(passwordLabel)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(newPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(retypeNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(retypePasswordLabel)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(cancelButton).addComponent(okButton)).addContainerGap(56, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel changePasswordTitle;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField retypeNewPasswordField;
    private javax.swing.JLabel retypePasswordLabel;
    private java.awt.TextField userNameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    public void addOkButtonListener(ActionListener listenForOkButton)
    {
        okButton.addActionListener(listenForOkButton);
    }

    public void addCancelButtonListener(ActionListener listenForCancelButton)
    {
        cancelButton.addActionListener(listenForCancelButton);
    }

    public String getUsernameField()
    {
        return this.userNameField.getText();
    }

    public char[] getPasswordField()
    {
        return this.passwordField.getPassword();
    }

    public char[] getNewPasswordField()
    {
        return this.newPasswordField.getPassword();
    }

    public char[] getRetypeNewPasswordFiled()
    {
        return this.retypeNewPasswordField.getPassword();
    }

    public void showMessage(String errorMessage)
    {
        JOptionPane.showMessageDialog(this, errorMessage);
    }

    public void clearFields()
    {
        userNameField.setText("");
        passwordField.setText("");
        newPasswordField.setText("");
        retypeNewPasswordField.setText("");
    }

}
